export type CandidateUpdateRequest = {
    id: string,
    email: string,
    password: string,
    name: string,
    gender: string,
    phone: string,
    birthDate: Date,
    cep: string,
    address: string,
    number: string,
    district: string,
    city: string,
    state: string,
}
